
import '../../../../auth/data/models/user_model.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'task_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'task_model.g.dart';

@freezed
class TaskModel with _$TaskModel{
  const factory TaskModel(
    int? id,
    String? createdAt,
    String? dueDate,
    String? title,
    String? description,
    bool? completed,
    String? image,
    @JsonKey(name: 'user')
    UserModel? user,
  ) = _TaskModel;

  factory TaskModel.fromJson(Map<String, dynamic> json) => _$TaskModelFromJson(json);
}