// This file is "main.dart"
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_model.g.dart';

@freezed
class UserModel with _$UserModel {
  
const factory UserModel({
    required String email,
    required String firstName,
     String? lastName,
    required String phoneNumber,
    required String address,
  })=_UserModel;

  factory UserModel.fromJson(Map<String, Object?> json)
      => _$UserModelFromJson(json);
}
